disabled = false
languageCode = "vi"
languageName = "Vietnamese"
weight = 1

[params]
  displayName = "VI"
  isoCode = "vi"
  rtl = false
  dateFormat = "2 January 2006"

[params.author]
   name = "Bùi Trung Tín"
   image = "profile.jpg"
   headline = "Một người thích học về những thứ lung tung"
   bio = "Sorry tui không giỏi xã giao" # appears in author card for each article
   links = [
    { github = "https://github.com/falconvn2006" }
   ]