[[main]]
  name = "Home"
  pageRef = "/"
  weight = 30

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40